### ISSUE TITLE
please help 

### ISSUE THREAD

**Issue by keemnine9** [dynamic2500/ps4-control-with-xbox360-controller-and-KB#2]
As I am wanting to access remote play with kb and mouse I am very noobie and I would very much appreciate if you would please have more details by: adding more links to what your supposed to download or for my fullest love would you care to make a video tutorial. thank you

**Comment by dynamic2500** [comment]
So sorry, i have no time to record video tutorial, i will take time to me.
Can you give me more detail about your troubles? what links cannot you download or some thing?
But i have to announce to you, the performance will not run perfectly as you expect if you don't do optimize tuning for you devices
